# ─────────────────────────────────────────────────────────────
#  Prod profile — Docker container (production server)
#  Start: docker compose -f docker-compose.app.yml up -d
# ─────────────────────────────────────────────────────────────
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/resource_service
    username: postgres
    password: "123cp!@#"

  data:
    redis:
      host: host.docker.internal
      port: 6379

  kafka:
    bootstrap-servers: host.docker.internal:9092

resource:
  storage:
    base-path: /app/storage
    base-url: http://localhost:6060
