# Local profile — fully local machine (PostgreSQL running on localhost)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: "123cp!@#"

  kafka:
    bootstrap-servers: localhost:9092

resource:
  storage:
    base-path: ./storage
    base-url: http://localhost:5000
