spring:
  datasource:
    url: jdbc:postgresql://165.22.247.142:5432/notification_service
    username: postgres
    password: Hour1819

  kafka:
    bootstrap-servers: localhost:9092

# In dev the app runs from the project root, so storage goes into ./storage
resource:
  storage:
    base-path: ./storage
    base-url: http://localhost:5000
  kafka:
    topics:
      upload: resource-file-upload
      delete: resource-file-delete
    consumer:
      group-id: resource-file-group
