# ─────────────────────────────────────────────────────────────
#  Local profile — IntelliJ on Mac/PC
#  PostgreSQL: docker compose -f docker-compose.postgres.yml up -d
#  Kafka+Redis: docker compose -f docker-compose.infra.yml up -d
# ─────────────────────────────────────────────────────────────
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: "Hour1819"

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

resource:
  storage:
    base-path: ./storage
    base-url: http://localhost:8080
