# Dev profile — app runs from project root (e.g. IntelliJ or mvn spring-boot:run)
spring:
  datasource:
    url: jdbc:postgresql://192.168.103.106:5432/notification_service
    username: postgres
    password: "123cp!@#"

  kafka:
    bootstrap-servers: localhost:9092

resource:
  storage:
    base-path: ./storage
    base-url: http://localhost:5000
